version=1.0.0
description=EPAM Report Portal. Mobitru plugin.
pluginId=mobitru
pluginClass=com.epam.reportportal.extension.mobitru.MobitruPlugin
pluginName=Mobitru
provider=EPAM Systems
license=Apache 2.0
documentation=https://reportportal.io/docs/plugins/
isIntegrationsAllowed=true
isEmbedded=true
isMultiple=true
mainBinaryData=main.js
metadataBinaryData=metadata.json
lombokVersion=1.18.42
springBootVersion=3.5.9
