version=1.0.0
description=Reinforce your ReportPortal instance with Mobitru integration and watch video of test executions right in the ReportPortal application.
pluginId=mobitru
pluginName=Mobitru
provider=EPAM Systems
license=Apache 2.0
documentation=https://reportportal.io/docs/plugins/
isIntegrationsAllowed=true
isEmbedded=true
isMultiple=true
mainBinaryData=main.js
metadataBinaryData=metadata.json
iconBinaryData=plugin-icon.svg
springBootVersion=3.5.16
