import reactHooks from "eslint-plugin-react-hooks";
import reactPlugin from "eslint-plugin-react";
import jsxA11yPlugin from "eslint-plugin-jsx-a11y";
import * as importX from "eslint-plugin-import-x";
import simpleImportSort from "eslint-plugin-simple-import-sort";
import prettierPlugin from "eslint-plugin-prettier";
import prettierConfig from "eslint-config-prettier";
import { fixupPluginRules, fixupConfigRules } from "@eslint/compat";
import globals from "globals";
import tseslint from "typescript-eslint";
import js from "@eslint/js";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

export default tseslint.config(
    {
        ignores: [
            "node_modules/*",
            "**/build",
            "**/package.json",
            "**/package-lock.json",
            "src/**/*.scss",
            "src/**/*.css",
        ],
    },

    js.configs.recommended,
    ...tseslint.configs.recommended,
    ...fixupConfigRules(reactPlugin.configs.flat.recommended),
    jsxA11yPlugin.flatConfigs.recommended,
    importX.flatConfigs.recommended,
    prettierConfig,

    {
        plugins: {
            "react-hooks": fixupPluginRules(reactHooks),
            "simple-import-sort": simpleImportSort,
            prettier: prettierPlugin,
        },

        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.es2021,
            },
            ecmaVersion: 2021,
            sourceType: "module",
            parserOptions: {
                ecmaFeatures: { jsx: true },
                project: "./tsconfig.json",
                tsconfigRootDir: __dirname,
            },
        },

        settings: {
            "import-x/resolver": {
                webpack: { config: path.join(__dirname, "webpack.config.js") },
            },
            react: { version: "18" },
        },

        rules: {
            //  React (overrides / additions to react/recommended)
            "react/react-in-jsx-scope": "off",
            "react/jsx-filename-extension": ["error", { extensions: [".ts", ".tsx"] }],
            "react/function-component-definition": ["error", { namedComponents: "arrow-function", unnamedComponents: "arrow-function" }],
            "react/prop-types": "error",
            "react/default-props-match-prop-types": "off",
            "react/forbid-prop-types": "off",
            "react/forbid-component-props": ["error", { forbid: ["propTypes", "defaultProps"] }],
            "react/require-default-props": ["error", { functions: "defaultArguments", ignoreFunctionalComponents: false }],
            "react/jsx-props-no-spreading": "off",
            "react/no-danger": "warn",
            "react/no-did-update-set-state": "error",
            "react/no-will-update-set-state": "error",
            "react/prefer-es6-class": ["error", "always"],
            "react/prefer-stateless-function": ["error", { ignorePureComponents: true }],
            "react/self-closing-comp": "error",
            "react/sort-comp": ["error", {
                order: ["static-variables", "static-methods", "instance-variables", "lifecycle", "/^handle.+$/", "/^on.+$/", "getters", "setters", "/^(get|set)(?!(InitialState$|DefaultProps$|ChildContext$)).+$/", "instance-methods", "everything-else", "rendering"],
                groups: {
                    lifecycle: ["displayName", "propTypes", "contextTypes", "childContextTypes", "mixins", "statics", "defaultProps", "constructor", "getDefaultProps", "getInitialState", "state", "getChildContext", "getDerivedStateFromProps", "componentWillMount", "UNSAFE_componentWillMount", "componentDidMount", "componentWillReceiveProps", "UNSAFE_componentWillReceiveProps", "shouldComponentUpdate", "componentWillUpdate", "UNSAFE_componentWillUpdate", "getSnapshotBeforeUpdate", "componentDidUpdate", "componentDidCatch", "componentWillUnmount"],
                    rendering: ["/^render.+$/", "render"],
                },
            }],
            "react/no-unused-prop-types": ["error", { customValidators: [], skipShapeProps: true }],
            "react/style-prop-object": "error",
            "react/no-array-index-key": "error",
            "react/forbid-foreign-prop-types": ["warn", { allowInPropTypes: true }],
            "react/void-dom-elements-no-children": "error",
            "react/no-redundant-should-component-update": "error",
            "react/no-unused-state": "error",
            "react/no-typos": "error",
            "react/jsx-curly-brace-presence": ["error", { props: "never", children: "never" }],
            "react/destructuring-assignment": ["error", "always"],
            "react/no-access-state-in-setstate": "error",
            "react/button-has-type": ["error", { button: true, submit: true, reset: false }],
            "react/no-this-in-sfc": "error",
            "react/jsx-fragments": ["error", "syntax"],
            "react/state-in-constructor": ["error", "always"],
            "react/static-property-placement": ["error", "property assignment"],
            "react/jsx-no-script-url": ["error", [{ name: "Link", props: ["to"] }]],
            "react/jsx-no-useless-fragment": "error",
            "react/jsx-no-constructed-context-values": "error",
            "react/no-unstable-nested-components": "error",
            "react/no-namespace": "error",
            "react/prefer-exact-props": "error",
            "react/no-arrow-function-lifecycle": "error",
            "react/no-invalid-html-attribute": "error",
            "react/no-unused-class-component-methods": "error",
            "react/jsx-pascal-case": ["error", { allowAllCaps: true, ignore: [] }],
            "react/jsx-no-bind": ["error", { ignoreRefs: true, allowArrowFunctions: true, allowFunctions: false, allowBind: false, ignoreDOMComponents: true }],

            //  React Hooks
            "react-hooks/rules-of-hooks": "error",
            "react-hooks/exhaustive-deps": "warn",

            //  TypeScript
            "@typescript-eslint/consistent-type-definitions": ["error", "interface"],
            "@typescript-eslint/no-explicit-any": "warn",
            "@typescript-eslint/no-use-before-define": "error",
            "@typescript-eslint/no-shadow": "error",

            //  import-x
            "import-x/no-unresolved": ["error", { ignore: ["^extensionProps/"] }],
            "import-x/no-named-as-default": "error",
            "import-x/no-named-as-default-member": "error",
            "import-x/no-extraneous-dependencies": ["error", {
                devDependencies: ["test/**", "tests/**", "spec/**", "**/__tests__/**", "**/__mocks__/**", "test.{js,jsx}", "test-*.{js,jsx}", "**/*{.,_}{test,spec}.{js,jsx}", "**/jest.config.js", "**/jest.setup.js", "**/webpack.config.js", "**/webpack.config.*.js"],
                optionalDependencies: false,
            }],
            "import-x/no-mutable-exports": "error",
            "import-x/no-amd": "error",
            "import-x/extensions": "off",
            "import-x/order": ["error", { groups: [["builtin", "external", "internal"]] }],
            "import-x/newline-after-import": "off",
            "import-x/prefer-default-export": "off",
            "import-x/no-absolute-path": "error",
            "import-x/no-dynamic-require": "error",
            "import-x/no-webpack-loader-syntax": "error",
            "import-x/no-relative-packages": "error",
            "import-x/no-import-module-exports": ["error", { exceptions: [] }],

            //  simple-import-sort
            "simple-import-sort/imports": "error",
            "simple-import-sort/exports": "error",

            //  Prettier
            "prettier/prettier": "error",

            //  Disable base rules superseded by TS equivalents
            "no-undef": "off",
            "no-use-before-define": "off",
            "no-shadow": "off",

            //  Best practices (from airbnb)
            "array-callback-return": ["error", { allowImplicit: true }],
            "block-scoped-var": "error",
            "consistent-return": "error",
            "curly": ["error", "multi-line"],
            "default-case": ["error", { commentPattern: "^no default$" }],
            "default-case-last": "error",
            "default-param-last": "error",
            "dot-notation": ["error", { allowKeywords: true }],
            "eqeqeq": ["error", "always", { null: "ignore" }],
            "grouped-accessor-pairs": "error",
            "guard-for-in": "error",
            "max-classes-per-file": ["error", 1],
            "no-alert": "warn",
            "no-caller": "error",
            "no-case-declarations": "error",
            "no-constructor-return": "error",
            "no-else-return": ["error", { allowElseIf: false }],
            "no-empty-pattern": "error",
            "no-eval": "error",
            "no-extend-native": "error",
            "no-extra-bind": "error",
            "no-extra-label": "error",
            "no-fallthrough": "error",
            "no-global-assign": ["error", { exceptions: [] }],
            "no-implied-eval": "error",
            "no-iterator": "error",
            "no-labels": ["error", { allowLoop: false, allowSwitch: false }],
            "no-lone-blocks": "error",
            "no-loop-func": "error",
            "no-multi-str": "error",
            "no-new": "error",
            "no-new-func": "error",
            "no-new-wrappers": "error",
            "no-octal": "error",
            "no-octal-escape": "error",
            "no-param-reassign": ["error", { props: true, ignorePropertyModificationsFor: ["acc", "accumulator", "e", "ctx", "context", "req", "request", "res", "response", "$scope", "staticContext"] }],
            "no-proto": "error",
            "no-restricted-properties": ["error",
                { object: "arguments", property: "callee", message: "arguments.callee is deprecated" },
                { object: "global", property: "isFinite", message: "Please use Number.isFinite instead" },
                { object: "self", property: "isFinite", message: "Please use Number.isFinite instead" },
                { object: "window", property: "isFinite", message: "Please use Number.isFinite instead" },
                { object: "global", property: "isNaN", message: "Please use Number.isNaN instead" },
                { object: "self", property: "isNaN", message: "Please use Number.isNaN instead" },
                { object: "window", property: "isNaN", message: "Please use Number.isNaN instead" },
                { property: "__defineGetter__", message: "Please use Object.defineProperty instead." },
                { property: "__defineSetter__", message: "Please use Object.defineProperty instead." },
                { object: "Math", property: "pow", message: "Use the exponentiation operator (**) instead." },
            ],
            "no-return-assign": ["error", "always"],
            "no-return-await": "error",
            "no-script-url": "error",
            "no-self-assign": ["error", { props: true }],
            "no-self-compare": "error",
            "no-sequences": "error",
            "no-unused-expressions": ["error", { allowShortCircuit: false, allowTernary: false, allowTaggedTemplates: false }],
            "no-unused-labels": "error",
            "no-useless-concat": "error",
            "no-useless-escape": "error",
            "no-useless-return": "error",
            "no-void": "error",
            "no-with": "error",
            "prefer-promise-reject-errors": ["error", { allowEmptyReject: true }],
            "prefer-regex-literals": ["error", { disallowRedundantWrapping: true }],
            "radix": "error",
            "vars-on-top": "error",
            "yoda": "error",
            "for-direction": "error",
            "no-async-promise-executor": "error",
            "no-await-in-loop": "error",
            "no-compare-neg-zero": "error",
            "no-cond-assign": ["error", "always"],
            "no-console": "warn",
            "no-constant-condition": "warn",
            "no-control-regex": "error",
            "no-debugger": "error",
            "no-dupe-else-if": "error",
            "no-empty-character-class": "error",
            "no-ex-assign": "error",
            "no-inner-declarations": "error",
            "no-invalid-regexp": "error",
            "no-promise-executor-return": "error",
            "no-prototype-builtins": "error",
            "no-regex-spaces": "error",
            "no-sparse-arrays": "error",
            "no-template-curly-in-string": "error",
            "no-unexpected-multiline": "error",
            "no-unreachable-loop": ["error", { ignore: [] }],
            "use-isnan": "error",
            "valid-typeof": ["error", { requireStringLiterals: true }],
            "camelcase": ["error", { properties: "never", ignoreDestructuring: false }],
            "func-names": "warn",
            "lines-between-class-members": ["error", "always", { exceptAfterSingleLine: false }],
            "new-cap": ["error", { newIsCap: true, newIsCapExceptions: [], capIsNew: false, capIsNewExceptions: ["Immutable.Map", "Immutable.Set", "Immutable.List"] }],
            "no-array-constructor": "error",
            "no-bitwise": "error",
            "no-continue": "error",
            "no-lonely-if": "error",
            "no-mixed-operators": ["error", {
                groups: [["%", "**"], ["%", "+"], ["%", "-"], ["%", "*"], ["%", "/"], ["/", "*"], ["&", "|", "<<", ">>", ">>>"], ["==", "!=", "===", "!=="], ["&&", "||"]],
                allowSamePrecedence: false,
            }],
            "no-multi-assign": ["error"],
            "no-nested-ternary": "error",
            "no-new-object": "error",
            "no-plusplus": "error",
            "no-underscore-dangle": ["error", { allow: ["__REDUX_DEVTOOLS_EXTENSION_COMPOSE__"], allowAfterThis: false, allowAfterSuper: false, enforceInMethodNames: true }],
            "no-unneeded-ternary": ["error", { defaultAssignment: false }],
            "one-var": ["error", "never"],
            "one-var-declaration-per-line": ["error", "always"],
            "operator-assignment": ["error", "always"],
            "prefer-exponentiation-operator": "error",
            "prefer-object-spread": "error",
            "unicode-bom": ["error", "never"],
            "no-delete-var": "error",
            "no-label-var": "error",
            "no-restricted-globals": ["error",
                { name: "isFinite", message: "Use Number.isFinite instead https://github.com/airbnb/javascript#standard-library--isfinite" },
                { name: "isNaN", message: "Use Number.isNaN instead https://github.com/airbnb/javascript#standard-library--isnan" },
                "addEventListener", "blur", "close", "closed", "confirm", "defaultStatus", "defaultstatus",
                "event", "external", "find", "focus", "frameElement", "frames", "history",
                "innerHeight", "innerWidth", "length", "location", "locationbar", "menubar",
                "moveBy", "moveTo", "name", "onblur", "onerror", "onfocus", "onload", "onresize",
                "onunload", "open", "opener", "opera", "outerHeight", "outerWidth", "pageXOffset",
                "pageYOffset", "parent", "print", "removeEventListener", "resizeBy", "resizeTo",
                "screen", "screenLeft", "screenTop", "screenX", "screenY", "scroll", "scrollbars",
                "scrollBy", "scrollTo", "scrollX", "scrollY", "self", "status", "statusbar",
                "stop", "toolbar", "top",
            ],
            "no-shadow-restricted-names": "error",
            "no-undef-init": "error",
            "arrow-body-style": ["error", "as-needed", { requireReturnForObjectLiteral: false }],
            "no-restricted-exports": ["error", { restrictedNamedExports: ["default", "then"] }],
            "no-useless-computed-key": "error",
            "no-useless-rename": ["error", { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false }],
            "no-var": "error",
            "object-shorthand": ["error", "always", { ignoreConstructors: false, avoidQuotes: true }],
            "prefer-arrow-callback": ["error", { allowNamedFunctions: false, allowUnboundThis: true }],
            "prefer-const": ["error", { destructuring: "any", ignoreReadBeforeAssign: true }],
            "prefer-destructuring": ["error", { VariableDeclarator: { array: false, object: true }, AssignmentExpression: { array: true, object: false } }, { enforceForRenamedProperties: false }],
            "prefer-numeric-literals": "error",
            "prefer-rest-params": "error",
            "prefer-spread": "error",
            "prefer-template": "error",
            "symbol-description": "error",
            "strict": ["error", "never"],

            //  Custom project rules
            "no-restricted-imports": ["error", {
                paths: [{ name: "prop-types", message: "Do not use prop-types in TypeScript components." }],
            }],
            "no-restricted-syntax": ["error",
                { selector: "ForInStatement", message: "for..in loops iterate over the entire prototype chain, which is virtually never what you want. Use Object.{keys,values,entries}, and iterate over the resulting array." },
                { selector: "ForOfStatement", message: "iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations." },
                { selector: "LabeledStatement", message: "Labels are a form of GOTO; using them makes code confusing and hard to maintain and understand." },
                { selector: "WithStatement", message: "`with` is disallowed in strict mode because it makes code impossible to predict and optimize." },
                { selector: "MemberExpression[property.name='propTypes']", message: "Do not assign or read Component.propTypes in TypeScript components." },
                { selector: "MemberExpression[property.name='defaultProps']", message: "Do not assign or read Component.defaultProps in TypeScript components." },
            ],
        },
    },
);
